M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-03-19T13:06:15-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-19T13:06:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.550
%
G90
G05
T1
X116.61Y-64.315
X122.39Y-64.315
T2
X101.7Y-138.01
X123.6Y-105.89
T3
X123.6Y-70.77
X139.6Y-101.25
T4
X101.7Y-74.61
X117.7Y-129.81
M30
