; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:batt_tester]
platform = atmelsam
board = battTester
framework = arduino
upload_protocol = sam-ba
; board_build.core = arduino
board_build.variant=battTester
board_build.variants_dir=variants
; board_build.mcu=at91samd21e15b
monitor_speed = 115200

build_flags =
    -D__SAMD21E15A__
    -D ARDUINO_SAMD_VARIANT_COMPLIANCE=10610 
    ; -D ARDUINO_SAMD21E15B
    ; -DATSAMD21E15B
    ; -Ivariants/battTester
        ; -I~/.platformio/packages/framework-arduinosam/cores/arduino
upload_flags =
    --offset=0x2000